### PR TITLE
fix(axios) usage

### PR DESCRIPTION
**Pull request by FerLuisxd**
Hello I saw your post at dev.to,
here is the fix.

You should be using the id to delete the method. check the [docs for json-server](https://www.npmjs.com/package/json-server)
image

### CODE REVIEW

**Comment by codingTheWorld777** [comment]
Hi Vilca, actually I've tried to use id to delete it but it didn't work too. Do you have any ideal?

**Comment by codingTheWorld777** [comment]
I see your comment doesn't right in my case. It is not a problem of json-server... it is the method of axios...

**Comment by codingTheWorld777** [comment]
Ah That's right. My mistake. Thank you very much 👌

**Comment by FerLuisxd** [comment]
the thing is that you send the object as a param, there is nothing wrong with axios. The thing is that you are using a route that is not recognized for your backend server (json-server) which is using simply "url"

**Comment by FerLuisxd** [comment]
your url is missing the id (this route exists and does the job you are trying to do)
I recommend you read the documentation of json-server to start using more deeply. 
Anyways really I didn't know json-server even existed, and good luck on this project!

**Pull request closed without merging**
